# Generated by Django 3.2.6 on 2021-08-26 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizacao', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('s', 'Atendido'), ('n', 'Não Atendido')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='')),
                ('tipo', models.CharField(choices=[('r', 'Recebido'), ('e', 'Enviado')], max_length=1)),
                ('status', models.CharField(choices=[('t', 'Entregue'), ('v', 'Enviado'), ('l', 'Lido')], max_length=1)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.atendimento')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente'),
        ),
    ]
